// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFk2IiOFRtkDHiBpjXt8pccbnbtNTyNo',
    appId: '1:504922945351:web:78c10ecf3d1862b289fe62',
    messagingSenderId: '504922945351',
    projectId: 'nutrisync-dev-2026-f3227',
    authDomain: 'nutrisync-dev-2026-f3227.firebaseapp.com',
    storageBucket: 'nutrisync-dev-2026-f3227.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuquqOrZLWV54TyqnUABSKel9isX4z0Tk',
    appId: '1:504922945351:android:95498d9f04df4a9b89fe62',
    messagingSenderId: '504922945351',
    projectId: 'nutrisync-dev-2026-f3227',
    storageBucket: 'nutrisync-dev-2026-f3227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2wRkbQ4BLRnF1lqVdREitmYT6S03xMxk',
    appId: '1:504922945351:ios:9ece60be50f56fe589fe62',
    messagingSenderId: '504922945351',
    projectId: 'nutrisync-dev-2026-f3227',
    storageBucket: 'nutrisync-dev-2026-f3227.firebasestorage.app',
    iosBundleId: 'com.example.nutrisyncProtal',
  );
}
